# Generated by Django 3.1.3 on 2021-05-01 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_usercontacts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercontacts',
            old_name='fooditem',
            new_name='contact',
        ),
    ]
