# Generated by Django 3.1.3 on 2021-05-01 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_auto_20210501_1908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercontacts',
            name='contact',
        ),
        migrations.AddField(
            model_name='usercontacts',
            name='address',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='usercontacts',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='usercontacts',
            name='full_name',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='usercontacts',
            name='phone_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='usercontacts',
            name='relationship',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
